module.exports = [
    "Accenture",
    "Netlink Software",
    "Stellar Technologies",
    "Embitel Technologies",
    "Diverse Lynx",
    "Circles",
    "Triniti Advanced Software Labs",
    "IBM",
    "Yash Technologies",
    "WSA Wonderful Sound for All",
    "Qvantel Software Solutions",
    "Dtcc",
    "Massmutual Global Business Services India",
    "Apple",
    "iii Consultig",
    "JPMorgan Chase Bank",
    "Tech Stalwart Solution",
    "Brand O Box",
    "Billmart Fintech",
    "Blossoms Solutions",
    "Signitives",
    "Palette69",
    "Hanivisu",
    "Currencies Direct",
    "Maig Innovations",
    "Smart Source",
    "Instasmart Software Solutions",
    "Grid Dynamics",
    "Logic Planet",
    "Hawk Sense Business Solutions",
    "Locomindstech",
    "Talent Cafe Solutions",
    "Annnetwork",
    "Priacc Innovations",
    "Whopper Technologies",
    "Mypcot Infotech",
    "Straina Technologies",
    "EVRY India Pvt Ltd",
    "Frisco Analytics",
    "Bristol Myers Squibb",
    "Squircle IT",
    "Enique It Solutions",
    "Photon",
    "Indium Software",
    "SmartDocs Business Solutions",
    "Client Server Tech",
    "anblicks",
    "Shanax Technologies",
    "Tquanta Technologies",
    "Tatwa Technologies",
    "Algonox Technologies",
    "Proounce",
    "Striketru Digital",
    "Aim Plus Services",
    "ODED Transformational Technologies Private Limited",
    "Arise Software Solutions",
    "Enliven Infotech",
    "Han Digital Solution",
    "Euclid Innovations",
    "H3 Technologies",
    "Dhatri Info Solutions",
    "Orchasp",
    "Infomerica",
    "ReddySys",
    "Star4rall It Solutions",
    "Drivetrain",
    "Highradius",
    "Swiss Re",
    "Charter Global",
    "Savina Software",
    "Cornerstone",
    "Cornerstone India",
    "Digitowork",
    "Baseforge Technologies",
    "Amphora Software",
    "Dynamic Technosoft",
    "Micronox Information Technologies",
    "Matchfinder Online Services",
    "Amazon",
    "Acheron Software Consultancy",
    "Transunion",
    "Aapmor Technologies",
    "Rarr Technologies",
    "ECS ME",
    "Nuacem AI",
    "Pipra Solutions",
    "Stryv Solutions",
    "Friesian Technologies",
    "Warner Bros. Discovery",
    "Techally Labs",
    "Two95 International",
    "CBL Solutions",
    "Iquest Solutions",
    "Unison Consulting",
    "Unison Group Com",
    "Lorven Technologies",
    "Iagami",
    "Blue Yonder",
    "Laddu Systems",
    "Savitr Software Services P",
    "Bharath Cloud",
    "Mocktheta",
    "Travash Software Solutions",
    "Kagami",
    "TechSophy, Inc",
    "IDESLABS",
    "Nxtwave Disruptive Technologies",
    "Brillius",
    "Zscaler LATAM",
    "YK Innosoft",
    "Tech Ringers",
    "Nextgen Infotech",
    "Tide Software",
    "Candescent",
    "Sixpath Technologies",
    "Birlasoft",
    "The Depository Trust & Clearing Corporation (DTCC)",
    "Nityo Infotech",
    "Virtualware Innovations",
    "TAO Digital",
    "Model N",
    "Amgen Inc",
    "[x]cube LABS",
    "DAZN",
    "Capgemini"
];