name: Naukri Auto Update

on:
  schedule:
    - cron: '30 1 * * *'   # 1:30 AM UTC = 7:00 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      # 🔥 Random delay (0–60 mins → 7:00 to 8:00 AM IST)
      # - name: Add random delay
      #   run: |
      #     echo "Adding random delay..."
      #     DELAY=$((RANDOM % 3600))
      #     echo "Sleeping for $DELAY seconds"
      #     sleep $DELAY

      # 🚀 Run your bot
      - name: Run Naukri bot
        run: node src/main.js
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          NAUKRI_HEADLINE_EVEN: ${{ secrets.NAUKRI_HEADLINE_EVEN }}
          NAUKRI_HEADLINE_ODD: ${{ secrets.NAUKRI_HEADLINE_ODD }}
          JOB_SEARCH_KEYWORD: ${{ secrets.JOB_SEARCH_KEYWORD }}

      # ❌ Upload screenshot on failure
      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: error.png